spring:
  application:
    name: finance

  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect